enum MinigameType {
  trivia,
  hangman,
  memory,
  runeForge,
  phishingClues,
  routeDecision,
  accessPuzzle,
  backupTimeline,
  narrativeChoice,
  orderSteps,
  alertClassification,
  shieldBoss,
  none,
}